// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webbutik.Models;

#nullable disable

namespace Webbutik.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221024104813_movieprice")]
    partial class movieprice
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CategoryMovie", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("CategoryMovie");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Webbutik.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Webbutik.Models.Category", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Webbutik.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Directors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InStock")
                        .HasColumnType("int");

                    b.Property<bool?>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Stars")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Writers")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description 1",
                            Directors = "Directors 1",
                            Discount = 25,
                            ImageUrl = "ImageUrl 1",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(7780),
                            Stars = "Stars 1",
                            Title = "Title 1",
                            Writers = "Writers 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description 2",
                            Directors = "Directors 2",
                            Discount = 25,
                            ImageUrl = "ImageUrl 2",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(7846),
                            Stars = "Stars 2",
                            Title = "Title 2",
                            Writers = "Writers 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description 3",
                            Directors = "Directors 3",
                            Discount = 25,
                            ImageUrl = "ImageUrl 3",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(7860),
                            Stars = "Stars 3",
                            Title = "Title 3",
                            Writers = "Writers 3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description 4",
                            Directors = "Directors 4",
                            Discount = 25,
                            ImageUrl = "ImageUrl 4",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(7873),
                            Stars = "Stars 4",
                            Title = "Title 4",
                            Writers = "Writers 4"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description 5",
                            Directors = "Directors 5",
                            Discount = 25,
                            ImageUrl = "ImageUrl 5",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(7886),
                            Stars = "Stars 5",
                            Title = "Title 5",
                            Writers = "Writers 5"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Description 6",
                            Directors = "Directors 6",
                            Discount = 25,
                            ImageUrl = "ImageUrl 6",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(7900),
                            Stars = "Stars 6",
                            Title = "Title 6",
                            Writers = "Writers 6"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Description 7",
                            Directors = "Directors 7",
                            Discount = 25,
                            ImageUrl = "ImageUrl 7",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(7913),
                            Stars = "Stars 7",
                            Title = "Title 7",
                            Writers = "Writers 7"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Description 8",
                            Directors = "Directors 8",
                            Discount = 25,
                            ImageUrl = "ImageUrl 8",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(7925),
                            Stars = "Stars 8",
                            Title = "Title 8",
                            Writers = "Writers 8"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Description 9",
                            Directors = "Directors 9",
                            Discount = 25,
                            ImageUrl = "ImageUrl 9",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(7938),
                            Stars = "Stars 9",
                            Title = "Title 9",
                            Writers = "Writers 9"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Description 10",
                            Directors = "Directors 10",
                            Discount = 25,
                            ImageUrl = "ImageUrl 10",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(7952),
                            Stars = "Stars 10",
                            Title = "Title 10",
                            Writers = "Writers 10"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Description 11",
                            Directors = "Directors 11",
                            Discount = 25,
                            ImageUrl = "ImageUrl 11",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(7965),
                            Stars = "Stars 11",
                            Title = "Title 11",
                            Writers = "Writers 11"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Description 12",
                            Directors = "Directors 12",
                            Discount = 25,
                            ImageUrl = "ImageUrl 12",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(7977),
                            Stars = "Stars 12",
                            Title = "Title 12",
                            Writers = "Writers 12"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Description 13",
                            Directors = "Directors 13",
                            Discount = 25,
                            ImageUrl = "ImageUrl 13",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(7989),
                            Stars = "Stars 13",
                            Title = "Title 13",
                            Writers = "Writers 13"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Description 14",
                            Directors = "Directors 14",
                            Discount = 25,
                            ImageUrl = "ImageUrl 14",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8048),
                            Stars = "Stars 14",
                            Title = "Title 14",
                            Writers = "Writers 14"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Description 15",
                            Directors = "Directors 15",
                            Discount = 25,
                            ImageUrl = "ImageUrl 15",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8061),
                            Stars = "Stars 15",
                            Title = "Title 15",
                            Writers = "Writers 15"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Description 16",
                            Directors = "Directors 16",
                            Discount = 25,
                            ImageUrl = "ImageUrl 16",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8073),
                            Stars = "Stars 16",
                            Title = "Title 16",
                            Writers = "Writers 16"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Description 17",
                            Directors = "Directors 17",
                            Discount = 25,
                            ImageUrl = "ImageUrl 17",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8085),
                            Stars = "Stars 17",
                            Title = "Title 17",
                            Writers = "Writers 17"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Description 18",
                            Directors = "Directors 18",
                            Discount = 25,
                            ImageUrl = "ImageUrl 18",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8099),
                            Stars = "Stars 18",
                            Title = "Title 18",
                            Writers = "Writers 18"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Description 19",
                            Directors = "Directors 19",
                            Discount = 25,
                            ImageUrl = "ImageUrl 19",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8111),
                            Stars = "Stars 19",
                            Title = "Title 19",
                            Writers = "Writers 19"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Description 20",
                            Directors = "Directors 20",
                            Discount = 25,
                            ImageUrl = "ImageUrl 20",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8124),
                            Stars = "Stars 20",
                            Title = "Title 20",
                            Writers = "Writers 20"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Description 21",
                            Directors = "Directors 21",
                            Discount = 25,
                            ImageUrl = "ImageUrl 21",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8136),
                            Stars = "Stars 21",
                            Title = "Title 21",
                            Writers = "Writers 21"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Description 22",
                            Directors = "Directors 22",
                            Discount = 25,
                            ImageUrl = "ImageUrl 22",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8148),
                            Stars = "Stars 22",
                            Title = "Title 22",
                            Writers = "Writers 22"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Description 23",
                            Directors = "Directors 23",
                            Discount = 25,
                            ImageUrl = "ImageUrl 23",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8161),
                            Stars = "Stars 23",
                            Title = "Title 23",
                            Writers = "Writers 23"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Description 24",
                            Directors = "Directors 24",
                            Discount = 25,
                            ImageUrl = "ImageUrl 24",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8174),
                            Stars = "Stars 24",
                            Title = "Title 24",
                            Writers = "Writers 24"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Description 25",
                            Directors = "Directors 25",
                            Discount = 25,
                            ImageUrl = "ImageUrl 25",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8186),
                            Stars = "Stars 25",
                            Title = "Title 25",
                            Writers = "Writers 25"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Description 26",
                            Directors = "Directors 26",
                            Discount = 25,
                            ImageUrl = "ImageUrl 26",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8198),
                            Stars = "Stars 26",
                            Title = "Title 26",
                            Writers = "Writers 26"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Description 27",
                            Directors = "Directors 27",
                            Discount = 25,
                            ImageUrl = "ImageUrl 27",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8276),
                            Stars = "Stars 27",
                            Title = "Title 27",
                            Writers = "Writers 27"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Description 28",
                            Directors = "Directors 28",
                            Discount = 25,
                            ImageUrl = "ImageUrl 28",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8290),
                            Stars = "Stars 28",
                            Title = "Title 28",
                            Writers = "Writers 28"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Description 29",
                            Directors = "Directors 29",
                            Discount = 25,
                            ImageUrl = "ImageUrl 29",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8302),
                            Stars = "Stars 29",
                            Title = "Title 29",
                            Writers = "Writers 29"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Description 30",
                            Directors = "Directors 30",
                            Discount = 25,
                            ImageUrl = "ImageUrl 30",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8315),
                            Stars = "Stars 30",
                            Title = "Title 30",
                            Writers = "Writers 30"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Description 31",
                            Directors = "Directors 31",
                            Discount = 25,
                            ImageUrl = "ImageUrl 31",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8328),
                            Stars = "Stars 31",
                            Title = "Title 31",
                            Writers = "Writers 31"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Description 32",
                            Directors = "Directors 32",
                            Discount = 25,
                            ImageUrl = "ImageUrl 32",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8340),
                            Stars = "Stars 32",
                            Title = "Title 32",
                            Writers = "Writers 32"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Description 33",
                            Directors = "Directors 33",
                            Discount = 25,
                            ImageUrl = "ImageUrl 33",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8352),
                            Stars = "Stars 33",
                            Title = "Title 33",
                            Writers = "Writers 33"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Description 34",
                            Directors = "Directors 34",
                            Discount = 25,
                            ImageUrl = "ImageUrl 34",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8365),
                            Stars = "Stars 34",
                            Title = "Title 34",
                            Writers = "Writers 34"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Description 35",
                            Directors = "Directors 35",
                            Discount = 25,
                            ImageUrl = "ImageUrl 35",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8379),
                            Stars = "Stars 35",
                            Title = "Title 35",
                            Writers = "Writers 35"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Description 36",
                            Directors = "Directors 36",
                            Discount = 25,
                            ImageUrl = "ImageUrl 36",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8392),
                            Stars = "Stars 36",
                            Title = "Title 36",
                            Writers = "Writers 36"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Description 37",
                            Directors = "Directors 37",
                            Discount = 25,
                            ImageUrl = "ImageUrl 37",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8404),
                            Stars = "Stars 37",
                            Title = "Title 37",
                            Writers = "Writers 37"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Description 38",
                            Directors = "Directors 38",
                            Discount = 25,
                            ImageUrl = "ImageUrl 38",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8416),
                            Stars = "Stars 38",
                            Title = "Title 38",
                            Writers = "Writers 38"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Description 39",
                            Directors = "Directors 39",
                            Discount = 25,
                            ImageUrl = "ImageUrl 39",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8466),
                            Stars = "Stars 39",
                            Title = "Title 39",
                            Writers = "Writers 39"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Description 40",
                            Directors = "Directors 40",
                            Discount = 25,
                            ImageUrl = "ImageUrl 40",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8481),
                            Stars = "Stars 40",
                            Title = "Title 40",
                            Writers = "Writers 40"
                        },
                        new
                        {
                            Id = 41,
                            Description = "Description 41",
                            Directors = "Directors 41",
                            Discount = 25,
                            ImageUrl = "ImageUrl 41",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8494),
                            Stars = "Stars 41",
                            Title = "Title 41",
                            Writers = "Writers 41"
                        },
                        new
                        {
                            Id = 42,
                            Description = "Description 42",
                            Directors = "Directors 42",
                            Discount = 25,
                            ImageUrl = "ImageUrl 42",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8506),
                            Stars = "Stars 42",
                            Title = "Title 42",
                            Writers = "Writers 42"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Description 43",
                            Directors = "Directors 43",
                            Discount = 25,
                            ImageUrl = "ImageUrl 43",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8519),
                            Stars = "Stars 43",
                            Title = "Title 43",
                            Writers = "Writers 43"
                        },
                        new
                        {
                            Id = 44,
                            Description = "Description 44",
                            Directors = "Directors 44",
                            Discount = 25,
                            ImageUrl = "ImageUrl 44",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8531),
                            Stars = "Stars 44",
                            Title = "Title 44",
                            Writers = "Writers 44"
                        },
                        new
                        {
                            Id = 45,
                            Description = "Description 45",
                            Directors = "Directors 45",
                            Discount = 25,
                            ImageUrl = "ImageUrl 45",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8543),
                            Stars = "Stars 45",
                            Title = "Title 45",
                            Writers = "Writers 45"
                        },
                        new
                        {
                            Id = 46,
                            Description = "Description 46",
                            Directors = "Directors 46",
                            Discount = 25,
                            ImageUrl = "ImageUrl 46",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8556),
                            Stars = "Stars 46",
                            Title = "Title 46",
                            Writers = "Writers 46"
                        },
                        new
                        {
                            Id = 47,
                            Description = "Description 47",
                            Directors = "Directors 47",
                            Discount = 25,
                            ImageUrl = "ImageUrl 47",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8568),
                            Stars = "Stars 47",
                            Title = "Title 47",
                            Writers = "Writers 47"
                        },
                        new
                        {
                            Id = 48,
                            Description = "Description 48",
                            Directors = "Directors 48",
                            Discount = 25,
                            ImageUrl = "ImageUrl 48",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8581),
                            Stars = "Stars 48",
                            Title = "Title 48",
                            Writers = "Writers 48"
                        },
                        new
                        {
                            Id = 49,
                            Description = "Description 49",
                            Directors = "Directors 49",
                            Discount = 25,
                            ImageUrl = "ImageUrl 49",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8593),
                            Stars = "Stars 49",
                            Title = "Title 49",
                            Writers = "Writers 49"
                        },
                        new
                        {
                            Id = 50,
                            Description = "Description 50",
                            Directors = "Directors 50",
                            Discount = 25,
                            ImageUrl = "ImageUrl 50",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8605),
                            Stars = "Stars 50",
                            Title = "Title 50",
                            Writers = "Writers 50"
                        },
                        new
                        {
                            Id = 51,
                            Description = "Description 51",
                            Directors = "Directors 51",
                            Discount = 25,
                            ImageUrl = "ImageUrl 51",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8617),
                            Stars = "Stars 51",
                            Title = "Title 51",
                            Writers = "Writers 51"
                        },
                        new
                        {
                            Id = 52,
                            Description = "Description 52",
                            Directors = "Directors 52",
                            Discount = 25,
                            ImageUrl = "ImageUrl 52",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8629),
                            Stars = "Stars 52",
                            Title = "Title 52",
                            Writers = "Writers 52"
                        },
                        new
                        {
                            Id = 53,
                            Description = "Description 53",
                            Directors = "Directors 53",
                            Discount = 25,
                            ImageUrl = "ImageUrl 53",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8683),
                            Stars = "Stars 53",
                            Title = "Title 53",
                            Writers = "Writers 53"
                        },
                        new
                        {
                            Id = 54,
                            Description = "Description 54",
                            Directors = "Directors 54",
                            Discount = 25,
                            ImageUrl = "ImageUrl 54",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8696),
                            Stars = "Stars 54",
                            Title = "Title 54",
                            Writers = "Writers 54"
                        },
                        new
                        {
                            Id = 55,
                            Description = "Description 55",
                            Directors = "Directors 55",
                            Discount = 25,
                            ImageUrl = "ImageUrl 55",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8708),
                            Stars = "Stars 55",
                            Title = "Title 55",
                            Writers = "Writers 55"
                        },
                        new
                        {
                            Id = 56,
                            Description = "Description 56",
                            Directors = "Directors 56",
                            Discount = 25,
                            ImageUrl = "ImageUrl 56",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8720),
                            Stars = "Stars 56",
                            Title = "Title 56",
                            Writers = "Writers 56"
                        },
                        new
                        {
                            Id = 57,
                            Description = "Description 57",
                            Directors = "Directors 57",
                            Discount = 25,
                            ImageUrl = "ImageUrl 57",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8733),
                            Stars = "Stars 57",
                            Title = "Title 57",
                            Writers = "Writers 57"
                        },
                        new
                        {
                            Id = 58,
                            Description = "Description 58",
                            Directors = "Directors 58",
                            Discount = 25,
                            ImageUrl = "ImageUrl 58",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8745),
                            Stars = "Stars 58",
                            Title = "Title 58",
                            Writers = "Writers 58"
                        },
                        new
                        {
                            Id = 59,
                            Description = "Description 59",
                            Directors = "Directors 59",
                            Discount = 25,
                            ImageUrl = "ImageUrl 59",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8758),
                            Stars = "Stars 59",
                            Title = "Title 59",
                            Writers = "Writers 59"
                        },
                        new
                        {
                            Id = 60,
                            Description = "Description 60",
                            Directors = "Directors 60",
                            Discount = 25,
                            ImageUrl = "ImageUrl 60",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8770),
                            Stars = "Stars 60",
                            Title = "Title 60",
                            Writers = "Writers 60"
                        },
                        new
                        {
                            Id = 61,
                            Description = "Description 61",
                            Directors = "Directors 61",
                            Discount = 25,
                            ImageUrl = "ImageUrl 61",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8782),
                            Stars = "Stars 61",
                            Title = "Title 61",
                            Writers = "Writers 61"
                        },
                        new
                        {
                            Id = 62,
                            Description = "Description 62",
                            Directors = "Directors 62",
                            Discount = 25,
                            ImageUrl = "ImageUrl 62",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8794),
                            Stars = "Stars 62",
                            Title = "Title 62",
                            Writers = "Writers 62"
                        },
                        new
                        {
                            Id = 63,
                            Description = "Description 63",
                            Directors = "Directors 63",
                            Discount = 25,
                            ImageUrl = "ImageUrl 63",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8807),
                            Stars = "Stars 63",
                            Title = "Title 63",
                            Writers = "Writers 63"
                        },
                        new
                        {
                            Id = 64,
                            Description = "Description 64",
                            Directors = "Directors 64",
                            Discount = 25,
                            ImageUrl = "ImageUrl 64",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8820),
                            Stars = "Stars 64",
                            Title = "Title 64",
                            Writers = "Writers 64"
                        },
                        new
                        {
                            Id = 65,
                            Description = "Description 65",
                            Directors = "Directors 65",
                            Discount = 25,
                            ImageUrl = "ImageUrl 65",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8833),
                            Stars = "Stars 65",
                            Title = "Title 65",
                            Writers = "Writers 65"
                        },
                        new
                        {
                            Id = 66,
                            Description = "Description 66",
                            Directors = "Directors 66",
                            Discount = 25,
                            ImageUrl = "ImageUrl 66",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8886),
                            Stars = "Stars 66",
                            Title = "Title 66",
                            Writers = "Writers 66"
                        },
                        new
                        {
                            Id = 67,
                            Description = "Description 67",
                            Directors = "Directors 67",
                            Discount = 25,
                            ImageUrl = "ImageUrl 67",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8899),
                            Stars = "Stars 67",
                            Title = "Title 67",
                            Writers = "Writers 67"
                        },
                        new
                        {
                            Id = 68,
                            Description = "Description 68",
                            Directors = "Directors 68",
                            Discount = 25,
                            ImageUrl = "ImageUrl 68",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8912),
                            Stars = "Stars 68",
                            Title = "Title 68",
                            Writers = "Writers 68"
                        },
                        new
                        {
                            Id = 69,
                            Description = "Description 69",
                            Directors = "Directors 69",
                            Discount = 25,
                            ImageUrl = "ImageUrl 69",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8924),
                            Stars = "Stars 69",
                            Title = "Title 69",
                            Writers = "Writers 69"
                        },
                        new
                        {
                            Id = 70,
                            Description = "Description 70",
                            Directors = "Directors 70",
                            Discount = 25,
                            ImageUrl = "ImageUrl 70",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8936),
                            Stars = "Stars 70",
                            Title = "Title 70",
                            Writers = "Writers 70"
                        },
                        new
                        {
                            Id = 71,
                            Description = "Description 71",
                            Directors = "Directors 71",
                            Discount = 25,
                            ImageUrl = "ImageUrl 71",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8948),
                            Stars = "Stars 71",
                            Title = "Title 71",
                            Writers = "Writers 71"
                        },
                        new
                        {
                            Id = 72,
                            Description = "Description 72",
                            Directors = "Directors 72",
                            Discount = 25,
                            ImageUrl = "ImageUrl 72",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8961),
                            Stars = "Stars 72",
                            Title = "Title 72",
                            Writers = "Writers 72"
                        },
                        new
                        {
                            Id = 73,
                            Description = "Description 73",
                            Directors = "Directors 73",
                            Discount = 25,
                            ImageUrl = "ImageUrl 73",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8973),
                            Stars = "Stars 73",
                            Title = "Title 73",
                            Writers = "Writers 73"
                        },
                        new
                        {
                            Id = 74,
                            Description = "Description 74",
                            Directors = "Directors 74",
                            Discount = 25,
                            ImageUrl = "ImageUrl 74",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8985),
                            Stars = "Stars 74",
                            Title = "Title 74",
                            Writers = "Writers 74"
                        },
                        new
                        {
                            Id = 75,
                            Description = "Description 75",
                            Directors = "Directors 75",
                            Discount = 25,
                            ImageUrl = "ImageUrl 75",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(8998),
                            Stars = "Stars 75",
                            Title = "Title 75",
                            Writers = "Writers 75"
                        },
                        new
                        {
                            Id = 76,
                            Description = "Description 76",
                            Directors = "Directors 76",
                            Discount = 25,
                            ImageUrl = "ImageUrl 76",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(9010),
                            Stars = "Stars 76",
                            Title = "Title 76",
                            Writers = "Writers 76"
                        },
                        new
                        {
                            Id = 77,
                            Description = "Description 77",
                            Directors = "Directors 77",
                            Discount = 25,
                            ImageUrl = "ImageUrl 77",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(9022),
                            Stars = "Stars 77",
                            Title = "Title 77",
                            Writers = "Writers 77"
                        },
                        new
                        {
                            Id = 78,
                            Description = "Description 78",
                            Directors = "Directors 78",
                            Discount = 25,
                            ImageUrl = "ImageUrl 78",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(9074),
                            Stars = "Stars 78",
                            Title = "Title 78",
                            Writers = "Writers 78"
                        },
                        new
                        {
                            Id = 79,
                            Description = "Description 79",
                            Directors = "Directors 79",
                            Discount = 25,
                            ImageUrl = "ImageUrl 79",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(9087),
                            Stars = "Stars 79",
                            Title = "Title 79",
                            Writers = "Writers 79"
                        },
                        new
                        {
                            Id = 80,
                            Description = "Description 80",
                            Directors = "Directors 80",
                            Discount = 25,
                            ImageUrl = "ImageUrl 80",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(9099),
                            Stars = "Stars 80",
                            Title = "Title 80",
                            Writers = "Writers 80"
                        },
                        new
                        {
                            Id = 81,
                            Description = "Description 81",
                            Directors = "Directors 81",
                            Discount = 25,
                            ImageUrl = "ImageUrl 81",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(9112),
                            Stars = "Stars 81",
                            Title = "Title 81",
                            Writers = "Writers 81"
                        },
                        new
                        {
                            Id = 82,
                            Description = "Description 82",
                            Directors = "Directors 82",
                            Discount = 25,
                            ImageUrl = "ImageUrl 82",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(9125),
                            Stars = "Stars 82",
                            Title = "Title 82",
                            Writers = "Writers 82"
                        },
                        new
                        {
                            Id = 83,
                            Description = "Description 83",
                            Directors = "Directors 83",
                            Discount = 25,
                            ImageUrl = "ImageUrl 83",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(9136),
                            Stars = "Stars 83",
                            Title = "Title 83",
                            Writers = "Writers 83"
                        },
                        new
                        {
                            Id = 84,
                            Description = "Description 84",
                            Directors = "Directors 84",
                            Discount = 25,
                            ImageUrl = "ImageUrl 84",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(9149),
                            Stars = "Stars 84",
                            Title = "Title 84",
                            Writers = "Writers 84"
                        },
                        new
                        {
                            Id = 85,
                            Description = "Description 85",
                            Directors = "Directors 85",
                            Discount = 25,
                            ImageUrl = "ImageUrl 85",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(9161),
                            Stars = "Stars 85",
                            Title = "Title 85",
                            Writers = "Writers 85"
                        },
                        new
                        {
                            Id = 86,
                            Description = "Description 86",
                            Directors = "Directors 86",
                            Discount = 25,
                            ImageUrl = "ImageUrl 86",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(9174),
                            Stars = "Stars 86",
                            Title = "Title 86",
                            Writers = "Writers 86"
                        },
                        new
                        {
                            Id = 87,
                            Description = "Description 87",
                            Directors = "Directors 87",
                            Discount = 25,
                            ImageUrl = "ImageUrl 87",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(9186),
                            Stars = "Stars 87",
                            Title = "Title 87",
                            Writers = "Writers 87"
                        },
                        new
                        {
                            Id = 88,
                            Description = "Description 88",
                            Directors = "Directors 88",
                            Discount = 25,
                            ImageUrl = "ImageUrl 88",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(9199),
                            Stars = "Stars 88",
                            Title = "Title 88",
                            Writers = "Writers 88"
                        },
                        new
                        {
                            Id = 89,
                            Description = "Description 89",
                            Directors = "Directors 89",
                            Discount = 25,
                            ImageUrl = "ImageUrl 89",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(9211),
                            Stars = "Stars 89",
                            Title = "Title 89",
                            Writers = "Writers 89"
                        },
                        new
                        {
                            Id = 90,
                            Description = "Description 90",
                            Directors = "Directors 90",
                            Discount = 25,
                            ImageUrl = "ImageUrl 90",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(9223),
                            Stars = "Stars 90",
                            Title = "Title 90",
                            Writers = "Writers 90"
                        },
                        new
                        {
                            Id = 91,
                            Description = "Description 91",
                            Directors = "Directors 91",
                            Discount = 25,
                            ImageUrl = "ImageUrl 91",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(9272),
                            Stars = "Stars 91",
                            Title = "Title 91",
                            Writers = "Writers 91"
                        },
                        new
                        {
                            Id = 92,
                            Description = "Description 92",
                            Directors = "Directors 92",
                            Discount = 25,
                            ImageUrl = "ImageUrl 92",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(9287),
                            Stars = "Stars 92",
                            Title = "Title 92",
                            Writers = "Writers 92"
                        },
                        new
                        {
                            Id = 93,
                            Description = "Description 93",
                            Directors = "Directors 93",
                            Discount = 25,
                            ImageUrl = "ImageUrl 93",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(9299),
                            Stars = "Stars 93",
                            Title = "Title 93",
                            Writers = "Writers 93"
                        },
                        new
                        {
                            Id = 94,
                            Description = "Description 94",
                            Directors = "Directors 94",
                            Discount = 25,
                            ImageUrl = "ImageUrl 94",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(9311),
                            Stars = "Stars 94",
                            Title = "Title 94",
                            Writers = "Writers 94"
                        },
                        new
                        {
                            Id = 95,
                            Description = "Description 95",
                            Directors = "Directors 95",
                            Discount = 25,
                            ImageUrl = "ImageUrl 95",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(9324),
                            Stars = "Stars 95",
                            Title = "Title 95",
                            Writers = "Writers 95"
                        },
                        new
                        {
                            Id = 96,
                            Description = "Description 96",
                            Directors = "Directors 96",
                            Discount = 25,
                            ImageUrl = "ImageUrl 96",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(9336),
                            Stars = "Stars 96",
                            Title = "Title 96",
                            Writers = "Writers 96"
                        },
                        new
                        {
                            Id = 97,
                            Description = "Description 97",
                            Directors = "Directors 97",
                            Discount = 25,
                            ImageUrl = "ImageUrl 97",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(9348),
                            Stars = "Stars 97",
                            Title = "Title 97",
                            Writers = "Writers 97"
                        },
                        new
                        {
                            Id = 98,
                            Description = "Description 98",
                            Directors = "Directors 98",
                            Discount = 25,
                            ImageUrl = "ImageUrl 98",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(9360),
                            Stars = "Stars 98",
                            Title = "Title 98",
                            Writers = "Writers 98"
                        },
                        new
                        {
                            Id = 99,
                            Description = "Description 99",
                            Directors = "Directors 99",
                            Discount = 25,
                            ImageUrl = "ImageUrl 99",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(9372),
                            Stars = "Stars 99",
                            Title = "Title 99",
                            Writers = "Writers 99"
                        },
                        new
                        {
                            Id = 100,
                            Description = "Description 100",
                            Directors = "Directors 100",
                            Discount = 25,
                            ImageUrl = "ImageUrl 100",
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 24, 12, 48, 13, 513, DateTimeKind.Local).AddTicks(9385),
                            Stars = "Stars 100",
                            Title = "Title 100",
                            Writers = "Writers 100"
                        });
                });

            modelBuilder.Entity("Webbutik.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderTotal")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Webbutik.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("CategoryMovie", b =>
                {
                    b.HasOne("Webbutik.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webbutik.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Webbutik.Models.CartItem", b =>
                {
                    b.HasOne("Webbutik.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Webbutik.Models.OrderDetail", b =>
                {
                    b.HasOne("Webbutik.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webbutik.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Webbutik.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
