// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webbutik.Models;

#nullable disable

namespace Webbutik.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CategoryMovie", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("CategoryMovie");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Webbutik.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Webbutik.Models.Category", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Webbutik.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ContentRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Directors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Discount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DiscountEnd")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DiscountPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DiscountStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImDbRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ImdbId")
                        .HasColumnType("int");

                    b.Property<int?>("InStock")
                        .HasColumnType("int");

                    b.Property<bool?>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RunTimeStr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stars")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContentRating = "ContentRating 1",
                            Description = "Description 1",
                            Directors = "Directors 1",
                            Discount = 25,
                            Genres = "Genres 1",
                            ImDbRating = "ImDbRating 1",
                            ImageUrl = "ImageUrl 1",
                            ImdbId = 1,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8486),
                            RunTimeStr = "RunTimeStr  1",
                            Stars = "Stars 1",
                            Title = "Title 1"
                        },
                        new
                        {
                            Id = 2,
                            ContentRating = "ContentRating 2",
                            Description = "Description 2",
                            Directors = "Directors 2",
                            Discount = 25,
                            Genres = "Genres 2",
                            ImDbRating = "ImDbRating 2",
                            ImageUrl = "ImageUrl 2",
                            ImdbId = 2,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8541),
                            RunTimeStr = "RunTimeStr  2",
                            Stars = "Stars 2",
                            Title = "Title 2"
                        },
                        new
                        {
                            Id = 3,
                            ContentRating = "ContentRating 3",
                            Description = "Description 3",
                            Directors = "Directors 3",
                            Discount = 25,
                            Genres = "Genres 3",
                            ImDbRating = "ImDbRating 3",
                            ImageUrl = "ImageUrl 3",
                            ImdbId = 3,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8556),
                            RunTimeStr = "RunTimeStr  3",
                            Stars = "Stars 3",
                            Title = "Title 3"
                        },
                        new
                        {
                            Id = 4,
                            ContentRating = "ContentRating 4",
                            Description = "Description 4",
                            Directors = "Directors 4",
                            Discount = 25,
                            Genres = "Genres 4",
                            ImDbRating = "ImDbRating 4",
                            ImageUrl = "ImageUrl 4",
                            ImdbId = 4,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8569),
                            RunTimeStr = "RunTimeStr  4",
                            Stars = "Stars 4",
                            Title = "Title 4"
                        },
                        new
                        {
                            Id = 5,
                            ContentRating = "ContentRating 5",
                            Description = "Description 5",
                            Directors = "Directors 5",
                            Discount = 25,
                            Genres = "Genres 5",
                            ImDbRating = "ImDbRating 5",
                            ImageUrl = "ImageUrl 5",
                            ImdbId = 5,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8581),
                            RunTimeStr = "RunTimeStr  5",
                            Stars = "Stars 5",
                            Title = "Title 5"
                        },
                        new
                        {
                            Id = 6,
                            ContentRating = "ContentRating 6",
                            Description = "Description 6",
                            Directors = "Directors 6",
                            Discount = 25,
                            Genres = "Genres 6",
                            ImDbRating = "ImDbRating 6",
                            ImageUrl = "ImageUrl 6",
                            ImdbId = 6,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8634),
                            RunTimeStr = "RunTimeStr  6",
                            Stars = "Stars 6",
                            Title = "Title 6"
                        },
                        new
                        {
                            Id = 7,
                            ContentRating = "ContentRating 7",
                            Description = "Description 7",
                            Directors = "Directors 7",
                            Discount = 25,
                            Genres = "Genres 7",
                            ImDbRating = "ImDbRating 7",
                            ImageUrl = "ImageUrl 7",
                            ImdbId = 7,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8647),
                            RunTimeStr = "RunTimeStr  7",
                            Stars = "Stars 7",
                            Title = "Title 7"
                        },
                        new
                        {
                            Id = 8,
                            ContentRating = "ContentRating 8",
                            Description = "Description 8",
                            Directors = "Directors 8",
                            Discount = 25,
                            Genres = "Genres 8",
                            ImDbRating = "ImDbRating 8",
                            ImageUrl = "ImageUrl 8",
                            ImdbId = 8,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8660),
                            RunTimeStr = "RunTimeStr  8",
                            Stars = "Stars 8",
                            Title = "Title 8"
                        },
                        new
                        {
                            Id = 9,
                            ContentRating = "ContentRating 9",
                            Description = "Description 9",
                            Directors = "Directors 9",
                            Discount = 25,
                            Genres = "Genres 9",
                            ImDbRating = "ImDbRating 9",
                            ImageUrl = "ImageUrl 9",
                            ImdbId = 9,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8673),
                            RunTimeStr = "RunTimeStr  9",
                            Stars = "Stars 9",
                            Title = "Title 9"
                        },
                        new
                        {
                            Id = 10,
                            ContentRating = "ContentRating 10",
                            Description = "Description 10",
                            Directors = "Directors 10",
                            Discount = 25,
                            Genres = "Genres 10",
                            ImDbRating = "ImDbRating 10",
                            ImageUrl = "ImageUrl 10",
                            ImdbId = 10,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8687),
                            RunTimeStr = "RunTimeStr  10",
                            Stars = "Stars 10",
                            Title = "Title 10"
                        },
                        new
                        {
                            Id = 11,
                            ContentRating = "ContentRating 11",
                            Description = "Description 11",
                            Directors = "Directors 11",
                            Discount = 25,
                            Genres = "Genres 11",
                            ImDbRating = "ImDbRating 11",
                            ImageUrl = "ImageUrl 11",
                            ImdbId = 11,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8700),
                            RunTimeStr = "RunTimeStr  11",
                            Stars = "Stars 11",
                            Title = "Title 11"
                        },
                        new
                        {
                            Id = 12,
                            ContentRating = "ContentRating 12",
                            Description = "Description 12",
                            Directors = "Directors 12",
                            Discount = 25,
                            Genres = "Genres 12",
                            ImDbRating = "ImDbRating 12",
                            ImageUrl = "ImageUrl 12",
                            ImdbId = 12,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8713),
                            RunTimeStr = "RunTimeStr  12",
                            Stars = "Stars 12",
                            Title = "Title 12"
                        },
                        new
                        {
                            Id = 13,
                            ContentRating = "ContentRating 13",
                            Description = "Description 13",
                            Directors = "Directors 13",
                            Discount = 25,
                            Genres = "Genres 13",
                            ImDbRating = "ImDbRating 13",
                            ImageUrl = "ImageUrl 13",
                            ImdbId = 13,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8726),
                            RunTimeStr = "RunTimeStr  13",
                            Stars = "Stars 13",
                            Title = "Title 13"
                        },
                        new
                        {
                            Id = 14,
                            ContentRating = "ContentRating 14",
                            Description = "Description 14",
                            Directors = "Directors 14",
                            Discount = 25,
                            Genres = "Genres 14",
                            ImDbRating = "ImDbRating 14",
                            ImageUrl = "ImageUrl 14",
                            ImdbId = 14,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8738),
                            RunTimeStr = "RunTimeStr  14",
                            Stars = "Stars 14",
                            Title = "Title 14"
                        },
                        new
                        {
                            Id = 15,
                            ContentRating = "ContentRating 15",
                            Description = "Description 15",
                            Directors = "Directors 15",
                            Discount = 25,
                            Genres = "Genres 15",
                            ImDbRating = "ImDbRating 15",
                            ImageUrl = "ImageUrl 15",
                            ImdbId = 15,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8780),
                            RunTimeStr = "RunTimeStr  15",
                            Stars = "Stars 15",
                            Title = "Title 15"
                        },
                        new
                        {
                            Id = 16,
                            ContentRating = "ContentRating 16",
                            Description = "Description 16",
                            Directors = "Directors 16",
                            Discount = 25,
                            Genres = "Genres 16",
                            ImDbRating = "ImDbRating 16",
                            ImageUrl = "ImageUrl 16",
                            ImdbId = 16,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8794),
                            RunTimeStr = "RunTimeStr  16",
                            Stars = "Stars 16",
                            Title = "Title 16"
                        },
                        new
                        {
                            Id = 17,
                            ContentRating = "ContentRating 17",
                            Description = "Description 17",
                            Directors = "Directors 17",
                            Discount = 25,
                            Genres = "Genres 17",
                            ImDbRating = "ImDbRating 17",
                            ImageUrl = "ImageUrl 17",
                            ImdbId = 17,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8807),
                            RunTimeStr = "RunTimeStr  17",
                            Stars = "Stars 17",
                            Title = "Title 17"
                        },
                        new
                        {
                            Id = 18,
                            ContentRating = "ContentRating 18",
                            Description = "Description 18",
                            Directors = "Directors 18",
                            Discount = 25,
                            Genres = "Genres 18",
                            ImDbRating = "ImDbRating 18",
                            ImageUrl = "ImageUrl 18",
                            ImdbId = 18,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8821),
                            RunTimeStr = "RunTimeStr  18",
                            Stars = "Stars 18",
                            Title = "Title 18"
                        },
                        new
                        {
                            Id = 19,
                            ContentRating = "ContentRating 19",
                            Description = "Description 19",
                            Directors = "Directors 19",
                            Discount = 25,
                            Genres = "Genres 19",
                            ImDbRating = "ImDbRating 19",
                            ImageUrl = "ImageUrl 19",
                            ImdbId = 19,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8834),
                            RunTimeStr = "RunTimeStr  19",
                            Stars = "Stars 19",
                            Title = "Title 19"
                        },
                        new
                        {
                            Id = 20,
                            ContentRating = "ContentRating 20",
                            Description = "Description 20",
                            Directors = "Directors 20",
                            Discount = 25,
                            Genres = "Genres 20",
                            ImDbRating = "ImDbRating 20",
                            ImageUrl = "ImageUrl 20",
                            ImdbId = 20,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8847),
                            RunTimeStr = "RunTimeStr  20",
                            Stars = "Stars 20",
                            Title = "Title 20"
                        },
                        new
                        {
                            Id = 21,
                            ContentRating = "ContentRating 21",
                            Description = "Description 21",
                            Directors = "Directors 21",
                            Discount = 25,
                            Genres = "Genres 21",
                            ImDbRating = "ImDbRating 21",
                            ImageUrl = "ImageUrl 21",
                            ImdbId = 21,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8859),
                            RunTimeStr = "RunTimeStr  21",
                            Stars = "Stars 21",
                            Title = "Title 21"
                        },
                        new
                        {
                            Id = 22,
                            ContentRating = "ContentRating 22",
                            Description = "Description 22",
                            Directors = "Directors 22",
                            Discount = 25,
                            Genres = "Genres 22",
                            ImDbRating = "ImDbRating 22",
                            ImageUrl = "ImageUrl 22",
                            ImdbId = 22,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8871),
                            RunTimeStr = "RunTimeStr  22",
                            Stars = "Stars 22",
                            Title = "Title 22"
                        },
                        new
                        {
                            Id = 23,
                            ContentRating = "ContentRating 23",
                            Description = "Description 23",
                            Directors = "Directors 23",
                            Discount = 25,
                            Genres = "Genres 23",
                            ImDbRating = "ImDbRating 23",
                            ImageUrl = "ImageUrl 23",
                            ImdbId = 23,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8884),
                            RunTimeStr = "RunTimeStr  23",
                            Stars = "Stars 23",
                            Title = "Title 23"
                        },
                        new
                        {
                            Id = 24,
                            ContentRating = "ContentRating 24",
                            Description = "Description 24",
                            Directors = "Directors 24",
                            Discount = 25,
                            Genres = "Genres 24",
                            ImDbRating = "ImDbRating 24",
                            ImageUrl = "ImageUrl 24",
                            ImdbId = 24,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8896),
                            RunTimeStr = "RunTimeStr  24",
                            Stars = "Stars 24",
                            Title = "Title 24"
                        },
                        new
                        {
                            Id = 25,
                            ContentRating = "ContentRating 25",
                            Description = "Description 25",
                            Directors = "Directors 25",
                            Discount = 25,
                            Genres = "Genres 25",
                            ImDbRating = "ImDbRating 25",
                            ImageUrl = "ImageUrl 25",
                            ImdbId = 25,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8939),
                            RunTimeStr = "RunTimeStr  25",
                            Stars = "Stars 25",
                            Title = "Title 25"
                        },
                        new
                        {
                            Id = 26,
                            ContentRating = "ContentRating 26",
                            Description = "Description 26",
                            Directors = "Directors 26",
                            Discount = 25,
                            Genres = "Genres 26",
                            ImDbRating = "ImDbRating 26",
                            ImageUrl = "ImageUrl 26",
                            ImdbId = 26,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8953),
                            RunTimeStr = "RunTimeStr  26",
                            Stars = "Stars 26",
                            Title = "Title 26"
                        },
                        new
                        {
                            Id = 27,
                            ContentRating = "ContentRating 27",
                            Description = "Description 27",
                            Directors = "Directors 27",
                            Discount = 25,
                            Genres = "Genres 27",
                            ImDbRating = "ImDbRating 27",
                            ImageUrl = "ImageUrl 27",
                            ImdbId = 27,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8966),
                            RunTimeStr = "RunTimeStr  27",
                            Stars = "Stars 27",
                            Title = "Title 27"
                        },
                        new
                        {
                            Id = 28,
                            ContentRating = "ContentRating 28",
                            Description = "Description 28",
                            Directors = "Directors 28",
                            Discount = 25,
                            Genres = "Genres 28",
                            ImDbRating = "ImDbRating 28",
                            ImageUrl = "ImageUrl 28",
                            ImdbId = 28,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8978),
                            RunTimeStr = "RunTimeStr  28",
                            Stars = "Stars 28",
                            Title = "Title 28"
                        },
                        new
                        {
                            Id = 29,
                            ContentRating = "ContentRating 29",
                            Description = "Description 29",
                            Directors = "Directors 29",
                            Discount = 25,
                            Genres = "Genres 29",
                            ImDbRating = "ImDbRating 29",
                            ImageUrl = "ImageUrl 29",
                            ImdbId = 29,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(8991),
                            RunTimeStr = "RunTimeStr  29",
                            Stars = "Stars 29",
                            Title = "Title 29"
                        },
                        new
                        {
                            Id = 30,
                            ContentRating = "ContentRating 30",
                            Description = "Description 30",
                            Directors = "Directors 30",
                            Discount = 25,
                            Genres = "Genres 30",
                            ImDbRating = "ImDbRating 30",
                            ImageUrl = "ImageUrl 30",
                            ImdbId = 30,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(9003),
                            RunTimeStr = "RunTimeStr  30",
                            Stars = "Stars 30",
                            Title = "Title 30"
                        },
                        new
                        {
                            Id = 31,
                            ContentRating = "ContentRating 31",
                            Description = "Description 31",
                            Directors = "Directors 31",
                            Discount = 25,
                            Genres = "Genres 31",
                            ImDbRating = "ImDbRating 31",
                            ImageUrl = "ImageUrl 31",
                            ImdbId = 31,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(9016),
                            RunTimeStr = "RunTimeStr  31",
                            Stars = "Stars 31",
                            Title = "Title 31"
                        },
                        new
                        {
                            Id = 32,
                            ContentRating = "ContentRating 32",
                            Description = "Description 32",
                            Directors = "Directors 32",
                            Discount = 25,
                            Genres = "Genres 32",
                            ImDbRating = "ImDbRating 32",
                            ImageUrl = "ImageUrl 32",
                            ImdbId = 32,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(9028),
                            RunTimeStr = "RunTimeStr  32",
                            Stars = "Stars 32",
                            Title = "Title 32"
                        },
                        new
                        {
                            Id = 33,
                            ContentRating = "ContentRating 33",
                            Description = "Description 33",
                            Directors = "Directors 33",
                            Discount = 25,
                            Genres = "Genres 33",
                            ImDbRating = "ImDbRating 33",
                            ImageUrl = "ImageUrl 33",
                            ImdbId = 33,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(9041),
                            RunTimeStr = "RunTimeStr  33",
                            Stars = "Stars 33",
                            Title = "Title 33"
                        },
                        new
                        {
                            Id = 34,
                            ContentRating = "ContentRating 34",
                            Description = "Description 34",
                            Directors = "Directors 34",
                            Discount = 25,
                            Genres = "Genres 34",
                            ImDbRating = "ImDbRating 34",
                            ImageUrl = "ImageUrl 34",
                            ImdbId = 34,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(9085),
                            RunTimeStr = "RunTimeStr  34",
                            Stars = "Stars 34",
                            Title = "Title 34"
                        },
                        new
                        {
                            Id = 35,
                            ContentRating = "ContentRating 35",
                            Description = "Description 35",
                            Directors = "Directors 35",
                            Discount = 25,
                            Genres = "Genres 35",
                            ImDbRating = "ImDbRating 35",
                            ImageUrl = "ImageUrl 35",
                            ImdbId = 35,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(9098),
                            RunTimeStr = "RunTimeStr  35",
                            Stars = "Stars 35",
                            Title = "Title 35"
                        },
                        new
                        {
                            Id = 36,
                            ContentRating = "ContentRating 36",
                            Description = "Description 36",
                            Directors = "Directors 36",
                            Discount = 25,
                            Genres = "Genres 36",
                            ImDbRating = "ImDbRating 36",
                            ImageUrl = "ImageUrl 36",
                            ImdbId = 36,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(9111),
                            RunTimeStr = "RunTimeStr  36",
                            Stars = "Stars 36",
                            Title = "Title 36"
                        },
                        new
                        {
                            Id = 37,
                            ContentRating = "ContentRating 37",
                            Description = "Description 37",
                            Directors = "Directors 37",
                            Discount = 25,
                            Genres = "Genres 37",
                            ImDbRating = "ImDbRating 37",
                            ImageUrl = "ImageUrl 37",
                            ImdbId = 37,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(9124),
                            RunTimeStr = "RunTimeStr  37",
                            Stars = "Stars 37",
                            Title = "Title 37"
                        },
                        new
                        {
                            Id = 38,
                            ContentRating = "ContentRating 38",
                            Description = "Description 38",
                            Directors = "Directors 38",
                            Discount = 25,
                            Genres = "Genres 38",
                            ImDbRating = "ImDbRating 38",
                            ImageUrl = "ImageUrl 38",
                            ImdbId = 38,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(9136),
                            RunTimeStr = "RunTimeStr  38",
                            Stars = "Stars 38",
                            Title = "Title 38"
                        },
                        new
                        {
                            Id = 39,
                            ContentRating = "ContentRating 39",
                            Description = "Description 39",
                            Directors = "Directors 39",
                            Discount = 25,
                            Genres = "Genres 39",
                            ImDbRating = "ImDbRating 39",
                            ImageUrl = "ImageUrl 39",
                            ImdbId = 39,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(9148),
                            RunTimeStr = "RunTimeStr  39",
                            Stars = "Stars 39",
                            Title = "Title 39"
                        },
                        new
                        {
                            Id = 40,
                            ContentRating = "ContentRating 40",
                            Description = "Description 40",
                            Directors = "Directors 40",
                            Discount = 25,
                            Genres = "Genres 40",
                            ImDbRating = "ImDbRating 40",
                            ImageUrl = "ImageUrl 40",
                            ImdbId = 40,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(9162),
                            RunTimeStr = "RunTimeStr  40",
                            Stars = "Stars 40",
                            Title = "Title 40"
                        },
                        new
                        {
                            Id = 41,
                            ContentRating = "ContentRating 41",
                            Description = "Description 41",
                            Directors = "Directors 41",
                            Discount = 25,
                            Genres = "Genres 41",
                            ImDbRating = "ImDbRating 41",
                            ImageUrl = "ImageUrl 41",
                            ImdbId = 41,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(9174),
                            RunTimeStr = "RunTimeStr  41",
                            Stars = "Stars 41",
                            Title = "Title 41"
                        },
                        new
                        {
                            Id = 42,
                            ContentRating = "ContentRating 42",
                            Description = "Description 42",
                            Directors = "Directors 42",
                            Discount = 25,
                            Genres = "Genres 42",
                            ImDbRating = "ImDbRating 42",
                            ImageUrl = "ImageUrl 42",
                            ImdbId = 42,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(9187),
                            RunTimeStr = "RunTimeStr  42",
                            Stars = "Stars 42",
                            Title = "Title 42"
                        },
                        new
                        {
                            Id = 43,
                            ContentRating = "ContentRating 43",
                            Description = "Description 43",
                            Directors = "Directors 43",
                            Discount = 25,
                            Genres = "Genres 43",
                            ImDbRating = "ImDbRating 43",
                            ImageUrl = "ImageUrl 43",
                            ImdbId = 43,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(9228),
                            RunTimeStr = "RunTimeStr  43",
                            Stars = "Stars 43",
                            Title = "Title 43"
                        },
                        new
                        {
                            Id = 44,
                            ContentRating = "ContentRating 44",
                            Description = "Description 44",
                            Directors = "Directors 44",
                            Discount = 25,
                            Genres = "Genres 44",
                            ImDbRating = "ImDbRating 44",
                            ImageUrl = "ImageUrl 44",
                            ImdbId = 44,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(9243),
                            RunTimeStr = "RunTimeStr  44",
                            Stars = "Stars 44",
                            Title = "Title 44"
                        },
                        new
                        {
                            Id = 45,
                            ContentRating = "ContentRating 45",
                            Description = "Description 45",
                            Directors = "Directors 45",
                            Discount = 25,
                            Genres = "Genres 45",
                            ImDbRating = "ImDbRating 45",
                            ImageUrl = "ImageUrl 45",
                            ImdbId = 45,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(9256),
                            RunTimeStr = "RunTimeStr  45",
                            Stars = "Stars 45",
                            Title = "Title 45"
                        },
                        new
                        {
                            Id = 46,
                            ContentRating = "ContentRating 46",
                            Description = "Description 46",
                            Directors = "Directors 46",
                            Discount = 25,
                            Genres = "Genres 46",
                            ImDbRating = "ImDbRating 46",
                            ImageUrl = "ImageUrl 46",
                            ImdbId = 46,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(9269),
                            RunTimeStr = "RunTimeStr  46",
                            Stars = "Stars 46",
                            Title = "Title 46"
                        },
                        new
                        {
                            Id = 47,
                            ContentRating = "ContentRating 47",
                            Description = "Description 47",
                            Directors = "Directors 47",
                            Discount = 25,
                            Genres = "Genres 47",
                            ImDbRating = "ImDbRating 47",
                            ImageUrl = "ImageUrl 47",
                            ImdbId = 47,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(9281),
                            RunTimeStr = "RunTimeStr  47",
                            Stars = "Stars 47",
                            Title = "Title 47"
                        },
                        new
                        {
                            Id = 48,
                            ContentRating = "ContentRating 48",
                            Description = "Description 48",
                            Directors = "Directors 48",
                            Discount = 25,
                            Genres = "Genres 48",
                            ImDbRating = "ImDbRating 48",
                            ImageUrl = "ImageUrl 48",
                            ImdbId = 48,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(9294),
                            RunTimeStr = "RunTimeStr  48",
                            Stars = "Stars 48",
                            Title = "Title 48"
                        },
                        new
                        {
                            Id = 49,
                            ContentRating = "ContentRating 49",
                            Description = "Description 49",
                            Directors = "Directors 49",
                            Discount = 25,
                            Genres = "Genres 49",
                            ImDbRating = "ImDbRating 49",
                            ImageUrl = "ImageUrl 49",
                            ImdbId = 49,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(9306),
                            RunTimeStr = "RunTimeStr  49",
                            Stars = "Stars 49",
                            Title = "Title 49"
                        },
                        new
                        {
                            Id = 50,
                            ContentRating = "ContentRating 50",
                            Description = "Description 50",
                            Directors = "Directors 50",
                            Discount = 25,
                            Genres = "Genres 50",
                            ImDbRating = "ImDbRating 50",
                            ImageUrl = "ImageUrl 50",
                            ImdbId = 50,
                            InStock = 1,
                            IsOnSale = true,
                            ReleaseDate = new DateTime(2022, 10, 31, 10, 50, 46, 973, DateTimeKind.Local).AddTicks(9319),
                            RunTimeStr = "RunTimeStr  50",
                            Stars = "Stars 50",
                            Title = "Title 50"
                        });
                });

            modelBuilder.Entity("Webbutik.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderTotal")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Webbutik.Models.OrderDetail", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Webbutik.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CategoryMovie", b =>
                {
                    b.HasOne("Webbutik.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webbutik.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Webbutik.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Webbutik.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webbutik.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Webbutik.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Webbutik.Models.CartItem", b =>
                {
                    b.HasOne("Webbutik.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Webbutik.Models.OrderDetail", b =>
                {
                    b.HasOne("Webbutik.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId");

                    b.HasOne("Webbutik.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId");

                    b.Navigation("Movie");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Webbutik.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
